version: 0.0
os: linux
files:
- source: /index.html
  destination: /var/www/html/

hooks:
 BeforeInstall:
    - location: scripts/apache2_install.sh
      timeout: 300
      runas: root

 ApplicationStop:
    - location: scripts/apache2_stop.sh
      timeout: 300
      runas: root
